### ISSUE TITLE
Esp-12f with micropython?

### ISSUE THREAD

**Issue by zigapovhe** [scs/smartmeter-datacollector#32]
Hi there! Congratulations on this awesome project! 

I have a few [SlimmeLezer+](https://www.zuidwijk.com/product/slimmelezer-plus/) laying around, and since it is basically impossible to get a Raspberry Pi these days (plus this custom board already has P1 port), I'm interested if it is possible to flash your firmware on ESP-12F chip with your python package I assume. Since we can't flash whole python program on a ESP, I would probably need to use MicroPython. Do you think that smartmeter-datacollector can work in a setup like that? Thanks for your help.

**Comment by raymar9** [comment]
Hi! Thank you!
Actually I find this idea of using our software on base of MicroPython interesting. That would expand the range of possible hardware platforms. 
I do not have any experience with MicroPython - have never tried it so far in a project. However after a quick glance on the MicroPython documentation, I highly doubt that our software runs with MicroPython out of the box without adapting it first. We use a couple of third-party libraries which need to support MicroPython as well or need to be replaced with MicroPython libraries that provide the same functionality. However this implies a lot of work. 
At the moment, you need something that runs classic Python on a Linux system.
